# atco.st
** Status:
*** 04-01-23:
- Because of potential for profit, considering doing something on this, in the initial list of projects I have.
  - Would be simple to set up a wordpress store, assemble inventory, and then just let people know I'm only shipping out 1 day a week, say on a Friday.

** Purpose:
- Sell things, mostly at cost.
- If I inflate prices, then I'll document how I'm doing so, to what amounts, and why.
- Just a transparent supply chain.
- Ideally run off donations. If not enough donations, I can potentially add a minimal "donation fee" to cover operation costs to items sold.
- Allows me to sell things I'm interested in to people - Direct to Consumer transactions.
- Build my network of people looking at things I'm interested.
- Promote Monero as a payment option.
- Also maybe get community involved. Like could get Homeless people, Elderly, or children, to solder some Dactyl Manuforms together for people, and they can make some money, and help out. Then when order is shipped, they can include a polaroid, saying "Assembled by X", to make it more personal. Just a way people can contribute, in a wholesome way, without acquiring labor through arbitrage techniques via leveraging lower labor costs of people in undeveloped countries.

** Current Ideas of Items that will be sold
*** Initial:
- Basic Dactyl Manuform Kits (unassembled, just one color, one keycap set, one type of mechanical switch for now)
   - https://github.com/greghab/Dactyl-Manuform-Build-Log
   - Note: Buy one of these, before we do this: https://dactyl.bigcartel.com/product/dactyl-manuform-5x6
      - Evaluate if this is good quality, as this would be competition (and I don't have to buy a 3d printer, and print this thing).
         - Ideally, I would have to be less time than them to shipment, and see if I can have lower costs (so price out how much I would see these kits for, relative to that cheaply assembled one).
      - Note: My value add, is that I can funnel people from my audience (YouTube, maybe blog), to my site atco.st, and sell them my kits. And I can ship out in < 1 week (maybe ship every friday), which is quicker return than 12-16 week backlog to build, and then shipping from Indonesia. Also, I offer the kit already scoped out for them, and shipped relatively quickly, reducing decision fatigue, and keeping things simple. So I'm selling "simplicity", for diyers, and those interested in getting their hands dirty. I don't have the means to do the labor for assembly currently.
*** Can expand to:
- More complicated Dactyl Manuforms (Hot Swappable switches, trackballs, etc)
  - https://github.com/Schievel1/dactyl_manuform_r_track
- QMK Trackballs
  - A Logitech M570 type of trackball, but with QMK, and using https://www.tindie.com/products/jkicklighter/pmw3360-motion-sensor/
- Sell Keyboard equipment (mechanical switches)
- PostmarketOS Phones (OnePlus6, Pocophone F1)
  - (Can maybe replace battery as well, put a screen protector on)
- Thinkpads with Libreboot/heads, etc.
- Other cool DIY stuff, that I can 3d print, assemble parts for, and sell kits for (kind of like what Adafruit is doing, but with less markup, more transparency, maybe more automation).
- *Custom Suspenders/vest "Utility Vest", with attachments:*
  - 1: Front laptop holder: like the: Custom DIY Connect-A-Desk Laptop Harness Walking Desk: https://www.amazon.com/gp/product/B00114W9X0
    - The current margins on these are quite high. And I can replace the black fabric, with options for different colors, designs
    - Can also maybe just drill hole in laptop, hook up detachable 2 prong strap, so it can hang, when not in use. Maybe fold out table.
  - 2: Rear laptop, USBC battery pouch. (or can attach to another location - velcro, etc).
    - Can also maybe have a central power, single USBC charger input, that distributes to rest of unit.
  - 3: Attachable screens (velcro), that can display stuff, tap into central power.
    - LED, OLED.
  - 4: Attachable infrared cameras, maybe GPS, other sensors. Can position in location on suspenders/vest.
- Clothes (in general) - no branding, except on tag.
  - Can maybe experiment with custom tailoring for a small fee (maybe robot).
- gaggiuino coffee maker kits
  - https://news.ycombinator.com/item?id=35354032
** Long Term Vision:
- Have an automated fulfillment system, for fulfilling orders (open source warehouse, and distribution).
  - So for electronic kits, have parts stored, conveyor belts, and have resistors bagged, arduinoes bagged, etc. Maybe even have it pack boxes automatically.
  - Have a way to automatically lube mechinical keyboard switches.
- Expand to holding other assets, such as forests, and selling fruits from that. Then I can sell X amount of firewood, maintain land, and be the caretaker of the land.
  - (Maybe also help wildlife, add sensors, raise bees, grow food and sell food, etc).

** How:
*** Website:
- WooCommerce: https://github.com/woocommerce/woocommerce
- monerowp: https://github.com/monero-integrations/monerowp
   - (For accepting monero payments).


* ltva permits:

https://www.blm.gov/documents/arizona-colorado-river-do-california-california-desert-do/public-room-frequently-requested
https://www.blm.gov/documents/arizona-colorado-river-do-california/public-room-frequently-requested/brochure/long-term

24. Vending Permits. You must have a vending permit to carry
on any commercial activity. Please contact the nearest BLM
office for information on vending or concession permits.

https://www.blm.gov/about/laws-and-regulations
- https://www.blm.gov/sites/default/files/docs/2022-11/FLPMA_2021.pdf

https://forums.iboats.com/threads/selling-food-out-on-the-water.436927/
